if filereadable("/etc/vimrc")
  source /etc/vimrc
endif

let mapleader = " "
colo typewriter
set relativenumber
set runtimepath^=~/02-me/vim/typewriter/vim-base/plugins
set ttyfast
nnoremap <leader>nn :NERDTreeToggle<CR>

function! PlaySound()
  silent! exec '!aplay -q ~/02-me/vim/typewriter/sounds/key01.aiff &'
endfunction
autocmd CursorMovedI * call PlaySound()
